spring:
  application:
    name: car-service
  docker:
    compose:
      file: C:\Users\ADMIN\Desktop\microservices-learn\root\car-service\compose.yaml
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8221/eureka/
okta:
  oauth2:
    issuer: https://dev-pzn0oc0dwqzld0pp.us.auth0.com/
    audience: ${okta.oauth2.issuer}api/v2/